sObjectDecorator/objects/Weather__c.object
<CustomObject>
    <fields>
        <fullName>Temperature__c</fullName>
        <label>Temperature</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Weather</label>
    <nameField>
        <label>City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

df12/sObjectDecorator/classes/weather_controller.cls
public class weather_controller {

	/* Custom controller */

	/* Property to display list of weather records */
    public List<DecoratedWeather> listOfWeather {
        get {
            if (listOfWeather == null) {
                listOfWeather = new List<DecoratedWeather>();
                
                for (Weather__c weather : [select name, temperature__c from Weather__c]) {
                    listOfWeather.add(new DecoratedWeather(weather));
                }
                
            }
            
            return listOfWeather;
        }
        
        private set;
    }
    
    /* Saves */
    public void SaveRecords() {
        List <Weather__c> weatherRecords = new List <Weather__c>();
        
        for (DecoratedWeather d : listOfWeather) {
            weatherRecords.add(d.weather);
        }          
        
        update weatherRecords;
    }

}