sObjectDecorator/objects/Weather__c.object
<CustomObject>
    <fields>
        <fullName>Temperature__c</fullName>
        <label>Temperature</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Weather</label>
    <nameField>
        <label>City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sObjectDecorator/classes/DecoratedWeather.cls
public with sharing class DecoratedWeather {

	/* class that wraps the weather custom object */

    public Weather__c weather { get; set; }
    public Decimal tempInCelcius { 
        get {
            if (weather != null && tempInCelcius == null )
                tempInCelcius = (5.0/9.0 * (weather.temperature__c - 32)).setScale(2);
                
            return tempInCelcius;
        } 
        set {
            if (weather != null && value != null ) {
                weather.temperature__c = ((9.0/5.0) * (value)).setScale(2) + 32;
            }
            tempInCelcius = value;
        }
    }
    
    public DecoratedWeather (Weather__c weather) {
        this.weather = weather;
    }
    

}